# Generated by Django 4.1.4 on 2022-12-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_userprofile_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='elements',
            field=models.JSONField(default=3),
            preserve_default=False,
        ),
    ]
