# Generated by Django 4.1.4 on 2022-12-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_userprofile_elements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='elements',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='symbol',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
