# Generated by Django 4.1.4 on 2022-12-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_remove_userprofile_elements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
