# Generated by Django 4.1.4 on 2022-12-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0007_userprofile_name_alter_userprofile_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='amount',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
    ]
