# Generated by Django 4.1.4 on 2022-12-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0008_alter_userprofile_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='to',
            field=models.CharField(default='THB', max_length=4),
            preserve_default=False,
        ),
    ]
